testApp/config/routes.rb
Rails.application.routes.draw do
  resources :articles  
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

testApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

testApp/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true,
                    length: { minimum: 5 }
end

testApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

testApp/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    
    def new
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
        end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

testApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

testApp/app/helpers/application_helper.rb
module ApplicationHelper
end

testApp/app/helpers/articles_helper.rb
module ArticlesHelper
end

testApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

testApp/app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

testApp/app/views/articles/new.html.erb
<hi>New Article</>

<%= form_for :article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

testApp/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

testApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

testApp/app/views/welcome/index.html.erb
<h1>Hello Danish</h1>

<%= link_to 'My Blog', controller: 'articles' %>

<%= link_to 'New article', new_article_path %>